* Miscellaneous
  :PROPERTIES:
  :SLIDE:    segue dark quote
  :ASIDE:    right bottom
  :ARTICLE:  flexbox vleft auto-fadein
  :END:

** Table
Add a =*= prefix to highlight item.   e.g. =* Highlight Item=
| Title1 | Title2            | Title2 |
|--------+-------------------+--------|
| Item1  | * Highlight Item  |     11 |
| Item2  | Shiroshime Kanata |   * 25 |
| Item3  | Test              |     56 |

#+BEGIN_SRC org
| Title1 | Title2            | Title2 |
|--------+-------------------+--------|
| Item1  | * Highlight Item  |     11 |
| Item2  | Shiroshime Kanata |   * 25 |
| Item3  | Test              |     56 |
#+END_SRC

** Footnote
Use =C-c C-x f= to create footnotes =[fn:N]=, which will be placed under a slide[fn:1]:
#+BEGIN_QUOTE
Jump between footnotes with =C-c C-c= on =[fn:N]=.
#+END_QUOTE
#+BEGIN_SRC org
 * Title
   This is content text.[fn:1]
...

 * Footnotes
 [fn:1] Footnote is in here!

#+END_SRC
#+ATTR_HTML: :class build
- *↓ Look here!*

** Math Formula
=org-ioslide= uses MathJax to render math formula:

$$\int_0^\infty e^{-x^2} dx=\frac{\sqrt{\pi}}{2}$$

#+BEGIN_SRC org
$$\int_0^\infty e^{-x^2} dx=\frac{\sqrt{\pi}}{2}$$
#+END_SRC
By default, MathJax is installed and enabled.

If you don't need this, just add =#+USE_MATHJAX: false= in your slide file to shrink slide size.

** Speaker Note
- Press =p= to display speaker note.
- Use =#+ATTR_HTML: :class note= before a QUOTE block, and its contents will be converted into speaker note:
#+BEGIN_SRC org
,#+ATTR_HTML: :class note
,#+BEGIN_QUOTE
This is the note area for presenter.
- Item 1
- Item 2
A [[https://github.com/][link]] to Github!
,#+END_QUOTE
#+END_SRC

#+ATTR_HTML: :class note
#+BEGIN_QUOTE
This is the note area for presenter.
- Item 1
- Item 2
A [[https://github.com/][link]] to Github!
#+END_QUOTE
